name: Daily Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-ubuntu-build
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run Build
        run: ./gradlew build

      - name: Create Plugin Zip
        run: ./gradlew buildPlugin

      - name: Get version and timestamp
        run: |
          NAME=$((grep -w 'name') < gradle.properties | cut -d= -f2)
          VERSION=$((grep -w 'version') < gradle.properties | cut -d= -f2)
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Unzip plugin into a temp directory
        run: |
          mkdir -p temp_dir
          unzip build/distributions/${{ env.NAME }}-${{ env.VERSION }}.zip -d temp_dir

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}-${{ env.VERSION }}
          path: temp_dir
