name: Plugin Verification Build

on:
  push:
    branches:
      - master
      - 2.[0-9]+.x
  workflow_dispatch:

jobs:
  verify-plugin:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-ubuntu-verify
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Plugin Verifier
        run: ./gradlew runPluginVerifier
